# Generated by Django 4.1.7 on 2023-06-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(max_length=11, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
        ),
    ]
